export default {
    ADD_TODO_ITEM: "ADD_TODO_ITEM",
    DELETE_TODO_ITEM: "DELETE_TODO_ITEM",
    EDIT_TODO_ITEM: "EDIT_TODO_ITEM",

    CREATE_TODO_LIST: "CREATE_TODO_LIST",
    DELETE_TODO_LIST: "DELETE_TODO_LIST",
    
}